### ISSUE TITLE
Mi Buds MI8 stopped working since January Update

### ISSUE THREAD

**Issue by tonyboy3** [PixelExperience/android-issues#1516]
Mi Buds MI8 stopped working since January Update

The App Recognise My Redmi Buds Pro 3 but no info are shown neither I can change the settings

**Comment by tonyboy3** [comment]
at bz.zaa.mibudsm8.MiuiHeadsetActivity.r(Unknown Source:105)
----
	at bz.zaa.mibudsm8.MiuiHeadsetActivity.onResume(Unknown Source:171)
----
M8BluetoothEngineImpl:Device:bluetoothDeviceExt{ mCurrentOpType: 3, Device Ble='Redmi Buds 3 Pro; 6C:D3:EE:0C:B3:B0, Device Edr ='Redmi Buds 3 Pro; 6C:D3:EE:0C:B3:B0, vid:0xffff, pid:0xffff, Status : MandatoryUpgrade:false, PowerMode:0, mChannelType:1, DualBackupFlag:-1, mRssi:-9999, mConnectType:0, mIsBoundByOtherDevice:false, mIsDirectlyConnectSpp:true, mIsEdrConnectedByOtherDevice:false, color type:0, count:0, mFailedReason:0x0}already on Connected list.Reconnect
find device:bluetoothDeviceExt{ mCurrentOpType: 3, Device Ble='Redmi Buds 3 Pro; 6C:D3:EE:0C:B3:B0, Device Edr ='Redmi Buds 3 Pro; 6C:D3:EE:0C:B3:B0, vid:0xffff, pid:0xffff, Status : MandatoryUpgrade:false, PowerMode:0, mChannelType:1, DualBackupFlag:-1, mRssi:-9999, mConnectType:0, mIsBoundByOtherDevice:false, mIsDirectlyConnectSpp:true, mIsEdrConnectedByOtherDevice:false, color type:0, count:0, mFailedReason:0x408}
device info:BluetoothDeviceInfo{ mCurrentOpType: 3 Device Ble='Redmi Buds 3 Pro; 6C:D3:EE:0C:B3:B0 Device Edr ='Redmi Buds 3 Pro; 6C:D3:EE:0C:B3:B0 vid:0xffff pid:0xffff MandatoryUpgrade:false channelStatus:0bleStatus:0 sppStatus:0 authStage:0 PowerMode:0 mBackUpMode:-1 isDeviceInfoUpdated:false authCmd:false FailedReason:0x408}
----
M8BluetoothBase:onConnection Find device :bluetoothDeviceExt{ mCurrentOpType: 3, Device Ble='Redmi Buds 3 Pro; 6C:D3:EE:0C:B3:B0, Device Edr ='Redmi Buds 3 Pro; 6C:D3:EE:0C:B3:B0, vid:0xffff, pid:0xffff, Status : MandatoryUpgrade:false, PowerMode:0, mChannelType:1, DualBackupFlag:-1, mRssi:-9999, mConnectType:0, mIsBoundByOtherDevice:false, mIsDirectlyConnectSpp:true, mIsEdrConnectedByOtherDevice:false, color type:0, count:0, mFailedReason:0x0}status:1
----
M8BluetoothEngineImpl:Device:bluetoothDeviceExt{ mCurrentOpType: 3, Device Ble='Redmi Buds 3 Pro; 6C:D3:EE:0C:B3:B0, Device Edr ='Redmi Buds 3 Pro; 6C:D3:EE:0C:B3:B0, vid:0xffff, pid:0xffff, Status : MandatoryUpgrade:false, PowerMode:0, mChannelType:1, DualBackupFlag:-1, mRssi:-9999, mConnectType:0, mIsBoundByOtherDevice:false, mIsDirectlyConnectSpp:true, mIsEdrConnectedByOtherDevice:false, color type:0, count:0, mFailedReason:0x0}already on Connected list.Reconnect
find device:bluetoothDeviceExt{ mCurrentOpType: 3, Device Ble='Redmi Buds 3 Pro; 6C:D3:EE:0C:B3:B0, Device Edr ='Redmi Buds 3 Pro; 6C:D3:EE:0C:B3:B0, vid:0xffff, pid:0xffff, Status : MandatoryUpgrade:false, PowerMode:0, mChannelType:1, DualBackupFlag:-1, mRssi:-9999, mConnectType:0, mIsBoundByOtherDevice:false, mIsDirectlyConnectSpp:true, mIsEdrConnectedByOtherDevice:false, color type:0, count:0, mFailedReason:0x0}
device info:BluetoothDeviceInfo{ mCurrentOpType: 3 Device Ble='Redmi Buds 3 Pro; 6C:D3:EE:0C:B3:B0 Device Edr ='Redmi Buds 3 Pro; 6C:D3:EE:0C:B3:B0 vid:0xffff pid:0xffff MandatoryUpgrade:false channelStatus:1bleStatus:0 sppStatus:1 authStage:0 PowerMode:0 mBackUpMode:-1 isDeviceInfoUpdated:false authCmd:false FailedReason:0x0}
----
M8BluetoothBase:onConnection Find device :bluetoothDeviceExt{ mCurrentOpType: 3, Device Ble='Redmi Buds 3 Pro; 6C:D3:EE:0C:B3:B0, Device Edr ='Redmi Buds 3 Pro; 6C:D3:EE:0C:B3:B0, vid:0xffff, pid:0xffff, Status : MandatoryUpgrade:false, PowerMode:0, mChannelType:1, DualBackupFlag:-1, mRssi:-9999, mConnectType:0, mIsBoundByOtherDevice:false, mIsDirectlyConnectSpp:true, mIsEdrConnectedByOtherDevice:false, color type:0, count:0, mFailedReason:0x0}status:1
----
M8BluetoothSpp:Current Spp Connecting DeviceBluetoothDeviceInfo{ mCurrentOpType: 3 Device Ble='Redmi Buds 3 Pro; 6C:D3:EE:0C:B3:B0 Device Edr ='Redmi Buds 3 Pro; 6C:D3:EE:0C:B3:B0 vid:0xffff pid:0xffff MandatoryUpgrade:false channelStatus:1bleStatus:0 sppStatus:1 authStage:0 PowerMode:0 mBackUpMode:-1 isDeviceInfoUpdated:false authCmd:false FailedReason:0x0} compare to BluetoothDeviceInfo{ mCurrentOpType: 3 Device Ble='Redmi Buds 3 Pro; 6C:D3:EE:0C:B3:B0 Device Edr ='Redmi Buds 3 Pro; 6C:D3:EE:0C:B3:B0 vid:0xffff pid:0xffff MandatoryUpgrade:false channelStatus:1bleStatus:0 sppStatus:1 authStage:0 PowerMode:0 mBackUpMode:-1 isDeviceInfoUpdated:false authCmd:false FailedReason:0x0}
----
M8BluetoothEngineImpl:Device:bluetoothDeviceExt{ mCurrentOpType: 3, Device Ble='Redmi Buds 3 Pro; 6C:D3:EE:0C:B3:B0, Device Edr ='Redmi Buds 3 Pro; 6C:D3:EE:0C:B3:B0, vid:0xffff, pid:0xffff, Status : MandatoryUpgrade:false, PowerMode:0, mChannelType:1, DualBackupFlag:-1, mRssi:-9999, mConnectType:0, mIsBoundByOtherDevice:false, mIsDirectlyConnectSpp:true, mIsEdrConnectedByOtherDevice:false, color type:0, count:0, mFailedReason:0x0}already on Connected list.Reconnect
find device:bluetoothDeviceExt{ mCurrentOpType: 3, Device Ble='Redmi Buds 3 Pro; 6C:D3:EE:0C:B3:B0, Device Edr ='Redmi Buds 3 Pro; 6C:D3:EE:0C:B3:B0, vid:0xffff, pid:0xffff, Status : MandatoryUpgrade:false, PowerMode:0, mChannelType:1, DualBackupFlag:-1, mRssi:-9999, mConnectType:0, mIsBoundByOtherDevice:false, mIsDirectlyConnectSpp:true, mIsEdrConnectedByOtherDevice:false, color type:0, count:0, mFailedReason:0x408}
device info:BluetoothDeviceInfo{ mCurrentOpType: 3 Device Ble='Redmi Buds 3 Pro; 6C:D3:EE:0C:B3:B0 Device Edr ='Redmi Buds 3 Pro; 6C:D3:EE:0C:B3:B0 vid:0xffff pid:0xffff MandatoryUpgrade:false channelStatus:1bleStatus:0 sppStatus:1 authStage:0 PowerMode:0 mBackUpMode:-1 isDeviceInfoUpdated:false authCmd:false FailedReason:0x408}
----
M8BluetoothBase:onConnection Find device :bluetoothDeviceExt{ mCurrentOpType: 3, Device Ble='Redmi Buds 3 Pro; 6C:D3:EE:0C:B3:B0, Device Edr ='Redmi Buds 3 Pro; 6C:D3:EE:0C:B3:B0, vid:0xffff, pid:0xffff, Status : MandatoryUpgrade:false, PowerMode:0, mChannelType:1, DualBackupFlag:-1, mRssi:-9999, mConnectType:0, mIsBoundByOtherDevice:false, mIsDirectlyConnectSpp:true, mIsEdrConnectedByOtherDevice:false, color type:0, count:0, mFailedReason:0x0}status:1
